"""AGX protocol package.

Public API for browser-safe AI ACTION messages and authenticated RESULT
messages.
"""

from .MSGv1 import (
    ACTION_KIND,
    RESULT_KIND,
    PROTOCOL_VERSION,
    PREFIX,
    AGXAuthenticationError,
    AGXError,
    AGXFormatError,
    AGXIntegrityError,
    AGXValidationError,
    Action,
    Result,
    create_action,
    create_result,
    decode_action,
    decode_result,
    encode_action,
    encode_result,
    extract_containers,
    new_command_id,
    new_hmac_secret,
    new_message_id,
    new_nonce,
    new_session_id,
    validate_action_dict,
    validate_result_dict,
)

__all__ = [
    "ACTION_KIND",
    "RESULT_KIND",
    "PROTOCOL_VERSION",
    "PREFIX",
    "AGXAuthenticationError",
    "AGXError",
    "AGXFormatError",
    "AGXIntegrityError",
    "AGXValidationError",
    "Action",
    "Result",
    "create_action",
    "create_result",
    "decode_action",
    "decode_result",
    "encode_action",
    "encode_result",
    "extract_containers",
    "new_command_id",
    "new_hmac_secret",
    "new_message_id",
    "new_nonce",
    "new_session_id",
    "validate_action_dict",
    "validate_result_dict",
]